name: tweet_webview_example
description: Demonstrates how to use the twitter_webview widget.
author: Larry Aasen <larryaasen@gmail.com>
version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  tweet_webview:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
