#.travis.yml
language: dart

dart:
  - dev
  - stable

dart_task:
  - test
  - dartfmt
  - dartanalyzer

after_script:
  - pub get
  - pub run test
  - pub global activate coverage
  - dart --pause-isolates-on-exit --enable-vm-service=9292 test/tweet_webview_test.dart &
  - pub global run coverage:collect_coverage --uri=http://127.0.0.1:9292/ -o coverage.json --resume-isolates
  - bash <(curl -s https://codecov.io/bash) -f coverage.json
